#!/bin/sh

. "$ZDOTDIR/alias.base"
. "$ZDOTDIR/alias.maths"
. "$ZDOTDIR/alias.device"
. "$ZDOTDIR/alias.nohup"
. "$ZDOTDIR/alias.dev"
. "$ZDOTDIR/alias.extension"

[ -f "$ZDOTDIR/alias.extra" ] && . "$ZDOTDIR/alias.extra"
