conky.config = {
    background = false,
    double_buffer = false,
    draw_borders = false,
    draw_outline = false,
    draw_shades = false,
    out_to_console = true,
    out_to_x = false,
    override_utf8_locale = false,
    own_window = false,
    short_units = true,
    if_up_strictness = 'address',
    cpu_avg_samples = 2,
    total_run_times = 0,
    update_interval = 5.0,
    use_spacer = 'right',
}
