PROFILE     = profile.zip
PROFILE_ENC = $(PROFILE).enc
KEY         = key.bin
KEY_ENC     = $(KEY).enc
PRVKEY      = ~/.ssh/id_rsa
PUBKEY      = ida_rsa.pub.pem

.PHONY: all
all: $(PROFILE_ENC) $(KEY_ENC)

$(PROFILE_ENC): $(PROFILE) $(KEY)
	openssl enc -aes-256-cbc -salt -in $< -out $@ -pass file:$(KEY)

$(PROFILE):
	git --git-dir="$$HOME/.config/dot/" --work-tree="$$HOME" reset; \
 	git --git-dir="$$HOME/.config/dot/" --work-tree="$$HOME" add default; \
	zip -9 $@ $$(git --git-dir="$$HOME/.config/dot/" --work-tree="$$HOME" status -s -b | grep -E '^A' | cut -c 4-); \
	git --git-dir="$$HOME/.config/dot/" --work-tree="$$HOME" reset

$(KEY_ENC): $(KEY) $(PUBKEY)
	openssl rsautl -encrypt -inkey $(PUBKEY) -pubin -in $< -out $@

$(KEY):
	openssl rand -base64 256 > $@

$(PUBKEY): $(PRVKEY)
	openssl rsa -in $< -outform pem > $@ -pubout

.PHONY: clean
clean:
	$(RM) $(PROFILE) $(PROFILE_ENC) $(KEY) $(KEY_ENC) $(PUBKEY)
